// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package smp

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"encoding/binary"
	"fmt"
	"bytes"
)


type Errors int
const (
	ErrorsOk Errors = 0
	ErrorsUnknown Errors = 1
	ErrorsNoMem Errors = 2
	ErrorsInval Errors = 3
	ErrorsTimeout Errors = 4
	ErrorsNoEnt Errors = 5
	ErrorsBadState Errors = 6
	ErrorsMsgSize Errors = 7
	ErrorsNotSup Errors = 8
	ErrorsCorrupt Errors = 9
	ErrorsBusy Errors = 10
	ErrorsAccessDenied Errors = 11
	ErrorsUnsupportedTooOld Errors = 12
	ErrorsUnsupportedTooNew Errors = 13
)
var values_Errors = map[Errors]string{0: "Ok", 1: "Unknown", 2: "NoMem", 3: "Inval", 4: "Timeout", 5: "NoEnt", 6: "BadState", 7: "MsgSize", 8: "NotSup", 9: "Corrupt", 10: "Busy", 11: "AccessDenied", 12: "UnsupportedTooOld", 13: "UnsupportedTooNew"}
var valueValues_Errors = []Errors{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13}
var valueNames_Errors = []string{"Ok", "Unknown", "NoMem", "Inval", "Timeout", "NoEnt", "BadState", "MsgSize", "NotSup", "Corrupt", "Busy", "AccessDenied", "UnsupportedTooOld", "UnsupportedTooNew"}
func (v Errors) isDefined() bool {
	_, ok := values_Errors[v]
	return ok
}
func (v Errors) IsAErrors() bool {
	return v.isDefined()
}
func (v Errors) String() string {
	name, ok := values_Errors[v]
	if ok {
		return name
	}
	return fmt.Sprintf("Errors(%d)", v)
}
func (v Errors) Title() string {
	if v.IsAErrors() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func ErrorsStrings() []string {
	return valueNames_Errors
}
func ErrorsValues() []Errors {
	return valueValues_Errors
}

type FsCommand int
const (
	FsCommandDownloadUpload FsCommand = 0
	FsCommandStatus FsCommand = 1
	FsCommandHash FsCommand = 2
	FsCommandSupportedHashTypes FsCommand = 3
	FsCommandClose FsCommand = 4
)
var values_FsCommand = map[FsCommand]string{0: "DownloadUpload", 1: "Status", 2: "Hash", 3: "SupportedHashTypes", 4: "Close"}
var valueValues_FsCommand = []FsCommand{0, 1, 2, 3, 4}
var valueNames_FsCommand = []string{"DownloadUpload", "Status", "Hash", "SupportedHashTypes", "Close"}
func (v FsCommand) isDefined() bool {
	_, ok := values_FsCommand[v]
	return ok
}
func (v FsCommand) IsAFsCommand() bool {
	return v.isDefined()
}
func (v FsCommand) String() string {
	name, ok := values_FsCommand[v]
	if ok {
		return name
	}
	return fmt.Sprintf("FsCommand(%d)", v)
}
func (v FsCommand) Title() string {
	if v.IsAFsCommand() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func FsCommandStrings() []string {
	return valueNames_FsCommand
}
func FsCommandValues() []FsCommand {
	return valueValues_FsCommand
}

type Group int
const (
	GroupOs Group = 0
	GroupImage Group = 1
	GroupStat Group = 2
	GroupSettings Group = 3
	GroupLog Group = 4
	GroupCrash Group = 5
	GroupSplit Group = 6
	GroupRun Group = 7
	GroupFs Group = 8
	GroupShell Group = 9
	GroupZephyr Group = 63
)
var values_Group = map[Group]string{0: "Os", 1: "Image", 2: "Stat", 3: "Settings", 4: "Log", 5: "Crash", 6: "Split", 7: "Run", 8: "Fs", 9: "Shell", 63: "Zephyr"}
var valueValues_Group = []Group{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 63}
var valueNames_Group = []string{"Os", "Image", "Stat", "Settings", "Log", "Crash", "Split", "Run", "Fs", "Shell", "Zephyr"}
func (v Group) isDefined() bool {
	_, ok := values_Group[v]
	return ok
}
func (v Group) IsAGroup() bool {
	return v.isDefined()
}
func (v Group) String() string {
	name, ok := values_Group[v]
	if ok {
		return name
	}
	return fmt.Sprintf("Group(%d)", v)
}
func (v Group) Title() string {
	if v.IsAGroup() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func GroupStrings() []string {
	return valueNames_Group
}
func GroupValues() []Group {
	return valueValues_Group
}

type ImageCommand int
const (
	ImageCommandState ImageCommand = 0
	ImageCommandUpload ImageCommand = 1
	ImageCommandFileImage ImageCommand = 2
	ImageCommandCoreList ImageCommand = 3
	ImageCommandCoreLoad ImageCommand = 4
	ImageCommandErase ImageCommand = 5
	ImageCommandSlotInfo ImageCommand = 6
)
var values_ImageCommand = map[ImageCommand]string{0: "State", 1: "Upload", 2: "FileImage", 3: "CoreList", 4: "CoreLoad", 5: "Erase", 6: "SlotInfo"}
var valueValues_ImageCommand = []ImageCommand{0, 1, 2, 3, 4, 5, 6}
var valueNames_ImageCommand = []string{"State", "Upload", "FileImage", "CoreList", "CoreLoad", "Erase", "SlotInfo"}
func (v ImageCommand) isDefined() bool {
	_, ok := values_ImageCommand[v]
	return ok
}
func (v ImageCommand) IsAImageCommand() bool {
	return v.isDefined()
}
func (v ImageCommand) String() string {
	name, ok := values_ImageCommand[v]
	if ok {
		return name
	}
	return fmt.Sprintf("ImageCommand(%d)", v)
}
func (v ImageCommand) Title() string {
	if v.IsAImageCommand() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func ImageCommandStrings() []string {
	return valueNames_ImageCommand
}
func ImageCommandValues() []ImageCommand {
	return valueValues_ImageCommand
}

type Operation int
const (
	OperationRead Operation = 0
	OperationReadResponse Operation = 1
	OperationWrite Operation = 2
	OperationWriteResponse Operation = 3
)
var values_Operation = map[Operation]string{0: "Read", 1: "ReadResponse", 2: "Write", 3: "WriteResponse"}
var valueValues_Operation = []Operation{0, 1, 2, 3}
var valueNames_Operation = []string{"Read", "ReadResponse", "Write", "WriteResponse"}
func (v Operation) isDefined() bool {
	_, ok := values_Operation[v]
	return ok
}
func (v Operation) IsAOperation() bool {
	return v.isDefined()
}
func (v Operation) String() string {
	name, ok := values_Operation[v]
	if ok {
		return name
	}
	return fmt.Sprintf("Operation(%d)", v)
}
func (v Operation) Title() string {
	if v.IsAOperation() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func OperationStrings() []string {
	return valueNames_Operation
}
func OperationValues() []Operation {
	return valueValues_Operation
}

type OsCommand int
const (
	OsCommandEcho OsCommand = 0
	OsCommandEchoControl OsCommand = 1
	OsCommandTaskStats OsCommand = 2
	OsCommandMempoolStats OsCommand = 3
	OsCommandDatetime OsCommand = 4
	OsCommandReset OsCommand = 5
	OsCommandParameters OsCommand = 6
	OsCommandOsAppInfo OsCommand = 7
	OsCommandBootloaderInfo OsCommand = 8
)
var values_OsCommand = map[OsCommand]string{0: "Echo", 1: "EchoControl", 2: "TaskStats", 3: "MempoolStats", 4: "Datetime", 5: "Reset", 6: "Parameters", 7: "OsAppInfo", 8: "BootloaderInfo"}
var valueValues_OsCommand = []OsCommand{0, 1, 2, 3, 4, 5, 6, 7, 8}
var valueNames_OsCommand = []string{"Echo", "EchoControl", "TaskStats", "MempoolStats", "Datetime", "Reset", "Parameters", "OsAppInfo", "BootloaderInfo"}
func (v OsCommand) isDefined() bool {
	_, ok := values_OsCommand[v]
	return ok
}
func (v OsCommand) IsAOsCommand() bool {
	return v.isDefined()
}
func (v OsCommand) String() string {
	name, ok := values_OsCommand[v]
	if ok {
		return name
	}
	return fmt.Sprintf("OsCommand(%d)", v)
}
func (v OsCommand) Title() string {
	if v.IsAOsCommand() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func OsCommandStrings() []string {
	return valueNames_OsCommand
}
func OsCommandValues() []OsCommand {
	return valueValues_OsCommand
}

type SettingsCommand int
const (
	SettingsCommandReadWrite SettingsCommand = 0
	SettingsCommandDelete SettingsCommand = 1
	SettingsCommandCommit SettingsCommand = 2
	SettingsCommandLoadSave SettingsCommand = 3
)
var values_SettingsCommand = map[SettingsCommand]string{0: "ReadWrite", 1: "Delete", 2: "Commit", 3: "LoadSave"}
var valueValues_SettingsCommand = []SettingsCommand{0, 1, 2, 3}
var valueNames_SettingsCommand = []string{"ReadWrite", "Delete", "Commit", "LoadSave"}
func (v SettingsCommand) isDefined() bool {
	_, ok := values_SettingsCommand[v]
	return ok
}
func (v SettingsCommand) IsASettingsCommand() bool {
	return v.isDefined()
}
func (v SettingsCommand) String() string {
	name, ok := values_SettingsCommand[v]
	if ok {
		return name
	}
	return fmt.Sprintf("SettingsCommand(%d)", v)
}
func (v SettingsCommand) Title() string {
	if v.IsASettingsCommand() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func SettingsCommandStrings() []string {
	return valueNames_SettingsCommand
}
func SettingsCommandValues() []SettingsCommand {
	return valueValues_SettingsCommand
}

type ShellCommand int
const (
	ShellCommandExecute ShellCommand = 0
)
var values_ShellCommand = map[ShellCommand]string{0: "Execute"}
var valueValues_ShellCommand = []ShellCommand{0}
var valueNames_ShellCommand = []string{"Execute"}
func (v ShellCommand) isDefined() bool {
	_, ok := values_ShellCommand[v]
	return ok
}
func (v ShellCommand) IsAShellCommand() bool {
	return v.isDefined()
}
func (v ShellCommand) String() string {
	name, ok := values_ShellCommand[v]
	if ok {
		return name
	}
	return fmt.Sprintf("ShellCommand(%d)", v)
}
func (v ShellCommand) Title() string {
	if v.IsAShellCommand() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func ShellCommandStrings() []string {
	return valueNames_ShellCommand
}
func ShellCommandValues() []ShellCommand {
	return valueValues_ShellCommand
}

type StatCommand int
const (
	StatCommandGroupData StatCommand = 0
	StatCommandListGroups StatCommand = 1
)
var values_StatCommand = map[StatCommand]string{0: "GroupData", 1: "ListGroups"}
var valueValues_StatCommand = []StatCommand{0, 1}
var valueNames_StatCommand = []string{"GroupData", "ListGroups"}
func (v StatCommand) isDefined() bool {
	_, ok := values_StatCommand[v]
	return ok
}
func (v StatCommand) IsAStatCommand() bool {
	return v.isDefined()
}
func (v StatCommand) String() string {
	name, ok := values_StatCommand[v]
	if ok {
		return name
	}
	return fmt.Sprintf("StatCommand(%d)", v)
}
func (v StatCommand) Title() string {
	if v.IsAStatCommand() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func StatCommandStrings() []string {
	return valueNames_StatCommand
}
func StatCommandValues() []StatCommand {
	return valueValues_StatCommand
}

type ZephyrCommand int
const (
	ZephyrCommandErase ZephyrCommand = 0
)
var values_ZephyrCommand = map[ZephyrCommand]string{0: "Erase"}
var valueValues_ZephyrCommand = []ZephyrCommand{0}
var valueNames_ZephyrCommand = []string{"Erase"}
func (v ZephyrCommand) isDefined() bool {
	_, ok := values_ZephyrCommand[v]
	return ok
}
func (v ZephyrCommand) IsAZephyrCommand() bool {
	return v.isDefined()
}
func (v ZephyrCommand) String() string {
	name, ok := values_ZephyrCommand[v]
	if ok {
		return name
	}
	return fmt.Sprintf("ZephyrCommand(%d)", v)
}
func (v ZephyrCommand) Title() string {
	if v.IsAZephyrCommand() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func ZephyrCommandStrings() []string {
	return valueNames_ZephyrCommand
}
func ZephyrCommandValues() []ZephyrCommand {
	return valueValues_ZephyrCommand
}
var Smp_Fields = []string{}
type Smp struct {
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent kaitai.Struct
	Debug_ map[string]*DebugData_
}
func NewWithParameters() *Smp {
	return &Smp{
	}
}

func (this Smp) IO_() *kaitai.Stream {
	return this._io
}

func (this *Smp) Read(io *kaitai.Stream, parent kaitai.Struct, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	return err
}

func NewSmp(data []byte) (*Smp, error) {
	o := &Smp{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Smp) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	return _t__bytes, err
}
var Fs_Fields = []string{"Command", "Payload"}
type Fs struct {
	Command FsCommand
	Payload []byte
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Message
	Debug_ map[string]*DebugData_
}
func NewFsWithParameters() *Fs {
	return &Fs{
	}
}

func (this Fs) IO_() *kaitai.Stream {
	return this._io
}

func (this *Fs) Read(io *kaitai.Stream, parent *Message, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Command"] = debugData_Start(this._io)
	tmp1, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Command = FsCommand(tmp1)
	this.Debug_["Command"].End, _ = this._io.Pos()
	this.Debug_["Payload"] = debugData_Start(this._io)
	tmp2, err := this._io.ReadBytes(int(this._parent.Length))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Payload = tmp2
	this.Debug_["Payload"].End, _ = this._io.Pos()
	return err
}

func NewFs(data []byte) (*Fs, error) {
	o := &Fs{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Fs) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, uint8(this.Command))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Payload)
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var Generic_Fields = []string{"Command", "Payload"}
type Generic struct {
	Command uint8
	Payload []byte
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Message
	Debug_ map[string]*DebugData_
}
func NewGenericWithParameters() *Generic {
	return &Generic{
	}
}

func (this Generic) IO_() *kaitai.Stream {
	return this._io
}

func (this *Generic) Read(io *kaitai.Stream, parent *Message, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Command"] = debugData_Start(this._io)
	tmp3, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Command = tmp3
	this.Debug_["Command"].End, _ = this._io.Pos()
	this.Debug_["Payload"] = debugData_Start(this._io)
	tmp4, err := this._io.ReadBytes(int(this._parent.Length))
	if err != nil {
		return err
	}
	tmp4 = tmp4
	this.Payload = tmp4
	this.Debug_["Payload"].End, _ = this._io.Pos()
	return err
}

func NewGeneric(data []byte) (*Generic, error) {
	o := &Generic{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Generic) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Command)
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Payload)
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var Image_Fields = []string{"Command", "Payload"}
type Image struct {
	Command ImageCommand
	Payload []byte
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Message
	Debug_ map[string]*DebugData_
}
func NewImageWithParameters() *Image {
	return &Image{
	}
}

func (this Image) IO_() *kaitai.Stream {
	return this._io
}

func (this *Image) Read(io *kaitai.Stream, parent *Message, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Command"] = debugData_Start(this._io)
	tmp5, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Command = ImageCommand(tmp5)
	this.Debug_["Command"].End, _ = this._io.Pos()
	this.Debug_["Payload"] = debugData_Start(this._io)
	tmp6, err := this._io.ReadBytes(int(this._parent.Length))
	if err != nil {
		return err
	}
	tmp6 = tmp6
	this.Payload = tmp6
	this.Debug_["Payload"].End, _ = this._io.Pos()
	return err
}

func NewImage(data []byte) (*Image, error) {
	o := &Image{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Image) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, uint8(this.Command))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Payload)
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var Message_Fields = []string{"Reserved", "Ver", "Op", "Flags", "Length", "Group", "Seq", "Body"}
type Message struct {
	Reserved uint64
	Ver uint64
	Op Operation
	Flags uint8
	Length uint16
	Group Group
	Seq uint8
	Body kaitai.Struct
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent kaitai.Struct
	Debug_ map[string]*DebugData_
}
func NewMessageWithParameters() *Message {
	return &Message{
	}
}

func (this Message) IO_() *kaitai.Stream {
	return this._io
}

func (this *Message) Read(io *kaitai.Stream, parent kaitai.Struct, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Reserved"] = debugData_Start(this._io)
	tmp7, err := this._io.ReadBitsIntBe(3)
	if err != nil {
		return err
	}
	this.Reserved = tmp7
	this.Debug_["Reserved"].End, _ = this._io.Pos()
	this.Debug_["Ver"] = debugData_Start(this._io)
	tmp8, err := this._io.ReadBitsIntBe(2)
	if err != nil {
		return err
	}
	this.Ver = tmp8
	this.Debug_["Ver"].End, _ = this._io.Pos()
	this.Debug_["Op"] = debugData_Start(this._io)
	tmp9, err := this._io.ReadBitsIntBe(3)
	if err != nil {
		return err
	}
	this.Op = Operation(tmp9)
	this.Debug_["Op"].End, _ = this._io.Pos()
	this._io.AlignToByte()
	this.Debug_["Flags"] = debugData_Start(this._io)
	tmp10, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Flags = tmp10
	this.Debug_["Flags"].End, _ = this._io.Pos()
	this.Debug_["Length"] = debugData_Start(this._io)
	tmp11, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Length = uint16(tmp11)
	this.Debug_["Length"].End, _ = this._io.Pos()
	this.Debug_["Group"] = debugData_Start(this._io)
	tmp12, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Group = Group(tmp12)
	this.Debug_["Group"].End, _ = this._io.Pos()
	this.Debug_["Seq"] = debugData_Start(this._io)
	tmp13, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Seq = tmp13
	this.Debug_["Seq"].End, _ = this._io.Pos()
	this.Debug_["Body"] = debugData_Start(this._io)
	switch (this.Group) {
	case GroupCrash:
		tmp14 := NewGenericWithParameters()
		err = tmp14.Read(this._io, this, this._root)
		this.Body = tmp14
		if err != nil {
			return err
		}
	case GroupFs:
		tmp15 := NewFsWithParameters()
		err = tmp15.Read(this._io, this, this._root)
		this.Body = tmp15
		if err != nil {
			return err
		}
	case GroupImage:
		tmp16 := NewImageWithParameters()
		err = tmp16.Read(this._io, this, this._root)
		this.Body = tmp16
		if err != nil {
			return err
		}
	case GroupLog:
		tmp17 := NewGenericWithParameters()
		err = tmp17.Read(this._io, this, this._root)
		this.Body = tmp17
		if err != nil {
			return err
		}
	case GroupOs:
		tmp18 := NewOsWithParameters()
		err = tmp18.Read(this._io, this, this._root)
		this.Body = tmp18
		if err != nil {
			return err
		}
	case GroupRun:
		tmp19 := NewGenericWithParameters()
		err = tmp19.Read(this._io, this, this._root)
		this.Body = tmp19
		if err != nil {
			return err
		}
	case GroupSettings:
		tmp20 := NewSettingsWithParameters()
		err = tmp20.Read(this._io, this, this._root)
		this.Body = tmp20
		if err != nil {
			return err
		}
	case GroupShell:
		tmp21 := NewShellWithParameters()
		err = tmp21.Read(this._io, this, this._root)
		this.Body = tmp21
		if err != nil {
			return err
		}
	case GroupSplit:
		tmp22 := NewGenericWithParameters()
		err = tmp22.Read(this._io, this, this._root)
		this.Body = tmp22
		if err != nil {
			return err
		}
	case GroupStat:
		tmp23 := NewStatWithParameters()
		err = tmp23.Read(this._io, this, this._root)
		this.Body = tmp23
		if err != nil {
			return err
		}
	case GroupZephyr:
		tmp24 := NewZephyrWithParameters()
		err = tmp24.Read(this._io, this, this._root)
		this.Body = tmp24
		if err != nil {
			return err
		}
	}
	this.Debug_["Body"].End, _ = this._io.Pos()
	return err
}

func NewMessage(data []byte) (*Message, error) {
	o := &Message{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Message) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	bitVal := []byte{}
	for i := range 3 {
		bitVal = append(bitVal, byte(1 & (uint64(this.Reserved) >> (3-i-1))))
	}
	for i := range 2 {
		bitVal = append(bitVal, byte(1 & (uint64(this.Ver) >> (2-i-1))))
	}
	for i := range 3 {
		bitVal = append(bitVal, byte(1 & (uint64(this.Op) >> (3-i-1))))
	}
	for i, j := 0, len(bitVal)-1; i < j; i, j = i+1, j-1 {
		bitVal[i], bitVal[j] = bitVal[j], bitVal[i]
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, flattenBitBytes(bitVal))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Flags)
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, uint16(this.Length))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, uint16(this.Group))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Seq)
	if err != nil {
		return _t__bytes, err
	}
	switch (this.Group) {
	case GroupCrash:
		if (this.Body != nil) {
			tmp25, err := this.Body.(*Generic).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp25)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupFs:
		if (this.Body != nil) {
			tmp26, err := this.Body.(*Fs).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp26)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupImage:
		if (this.Body != nil) {
			tmp27, err := this.Body.(*Image).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp27)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupLog:
		if (this.Body != nil) {
			tmp28, err := this.Body.(*Generic).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp28)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupOs:
		if (this.Body != nil) {
			tmp29, err := this.Body.(*Os).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp29)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupRun:
		if (this.Body != nil) {
			tmp30, err := this.Body.(*Generic).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp30)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupSettings:
		if (this.Body != nil) {
			tmp31, err := this.Body.(*Settings).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp31)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupShell:
		if (this.Body != nil) {
			tmp32, err := this.Body.(*Shell).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp32)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupSplit:
		if (this.Body != nil) {
			tmp33, err := this.Body.(*Generic).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp33)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupStat:
		if (this.Body != nil) {
			tmp34, err := this.Body.(*Stat).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp34)
			if err != nil {
				return _t__bytes, err
			}
		}
	case GroupZephyr:
		if (this.Body != nil) {
			tmp35, err := this.Body.(*Zephyr).Bytes_()
			if err != nil {
				return _t__bytes, err
			}
			_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, tmp35)
			if err != nil {
				return _t__bytes, err
			}
		}
	}
	return _t__bytes, err
}
var Os_Fields = []string{"Command", "Payload"}
type Os struct {
	Command OsCommand
	Payload []byte
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Message
	Debug_ map[string]*DebugData_
}
func NewOsWithParameters() *Os {
	return &Os{
	}
}

func (this Os) IO_() *kaitai.Stream {
	return this._io
}

func (this *Os) Read(io *kaitai.Stream, parent *Message, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Command"] = debugData_Start(this._io)
	tmp36, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Command = OsCommand(tmp36)
	this.Debug_["Command"].End, _ = this._io.Pos()
	this.Debug_["Payload"] = debugData_Start(this._io)
	tmp37, err := this._io.ReadBytes(int(this._parent.Length))
	if err != nil {
		return err
	}
	tmp37 = tmp37
	this.Payload = tmp37
	this.Debug_["Payload"].End, _ = this._io.Pos()
	return err
}

func NewOs(data []byte) (*Os, error) {
	o := &Os{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Os) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, uint8(this.Command))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Payload)
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var Settings_Fields = []string{"Command", "Payload"}
type Settings struct {
	Command SettingsCommand
	Payload []byte
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Message
	Debug_ map[string]*DebugData_
}
func NewSettingsWithParameters() *Settings {
	return &Settings{
	}
}

func (this Settings) IO_() *kaitai.Stream {
	return this._io
}

func (this *Settings) Read(io *kaitai.Stream, parent *Message, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Command"] = debugData_Start(this._io)
	tmp38, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Command = SettingsCommand(tmp38)
	this.Debug_["Command"].End, _ = this._io.Pos()
	this.Debug_["Payload"] = debugData_Start(this._io)
	tmp39, err := this._io.ReadBytes(int(this._parent.Length))
	if err != nil {
		return err
	}
	tmp39 = tmp39
	this.Payload = tmp39
	this.Debug_["Payload"].End, _ = this._io.Pos()
	return err
}

func NewSettings(data []byte) (*Settings, error) {
	o := &Settings{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Settings) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, uint8(this.Command))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Payload)
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var Shell_Fields = []string{"Command", "Payload"}
type Shell struct {
	Command ShellCommand
	Payload []byte
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Message
	Debug_ map[string]*DebugData_
}
func NewShellWithParameters() *Shell {
	return &Shell{
	}
}

func (this Shell) IO_() *kaitai.Stream {
	return this._io
}

func (this *Shell) Read(io *kaitai.Stream, parent *Message, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Command"] = debugData_Start(this._io)
	tmp40, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Command = ShellCommand(tmp40)
	this.Debug_["Command"].End, _ = this._io.Pos()
	this.Debug_["Payload"] = debugData_Start(this._io)
	tmp41, err := this._io.ReadBytes(int(this._parent.Length))
	if err != nil {
		return err
	}
	tmp41 = tmp41
	this.Payload = tmp41
	this.Debug_["Payload"].End, _ = this._io.Pos()
	return err
}

func NewShell(data []byte) (*Shell, error) {
	o := &Shell{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Shell) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, uint8(this.Command))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Payload)
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var Stat_Fields = []string{"Command", "Payload"}
type Stat struct {
	Command StatCommand
	Payload []byte
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Message
	Debug_ map[string]*DebugData_
}
func NewStatWithParameters() *Stat {
	return &Stat{
	}
}

func (this Stat) IO_() *kaitai.Stream {
	return this._io
}

func (this *Stat) Read(io *kaitai.Stream, parent *Message, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Command"] = debugData_Start(this._io)
	tmp42, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Command = StatCommand(tmp42)
	this.Debug_["Command"].End, _ = this._io.Pos()
	this.Debug_["Payload"] = debugData_Start(this._io)
	tmp43, err := this._io.ReadBytes(int(this._parent.Length))
	if err != nil {
		return err
	}
	tmp43 = tmp43
	this.Payload = tmp43
	this.Debug_["Payload"].End, _ = this._io.Pos()
	return err
}

func NewStat(data []byte) (*Stat, error) {
	o := &Stat{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Stat) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, uint8(this.Command))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Payload)
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var Zephyr_Fields = []string{"Command", "Payload"}
type Zephyr struct {
	Command ZephyrCommand
	Payload []byte
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Message
	Debug_ map[string]*DebugData_
}
func NewZephyrWithParameters() *Zephyr {
	return &Zephyr{
	}
}

func (this Zephyr) IO_() *kaitai.Stream {
	return this._io
}

func (this *Zephyr) Read(io *kaitai.Stream, parent *Message, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Command"] = debugData_Start(this._io)
	tmp44, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Command = ZephyrCommand(tmp44)
	this.Debug_["Command"].End, _ = this._io.Pos()
	this.Debug_["Payload"] = debugData_Start(this._io)
	tmp45, err := this._io.ReadBytes(int(this._parent.Length))
	if err != nil {
		return err
	}
	tmp45 = tmp45
	this.Payload = tmp45
	this.Debug_["Payload"].End, _ = this._io.Pos()
	return err
}

func NewZephyr(data []byte) (*Zephyr, error) {
	o := &Zephyr{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Zephyr) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, uint8(this.Command))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.BigEndian, this.Payload)
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var DefinedEnumValues = map[interface{}][]int{Errors(0):{0,1,2,3,4,5,6,7,8,9,10,11,12,13},FsCommand(0):{0,1,2,3,4},Group(0):{0,1,2,3,4,5,6,7,8,9,63},ImageCommand(0):{0,1,2,3,4,5,6},Operation(0):{0,1,2,3},OsCommand(0):{0,1,2,3,4,5,6,7,8},SettingsCommand(0):{0,1,2,3},ShellCommand(0):{0},StatCommand(0):{0,1},ZephyrCommand(0):{0}}
type DebugData_ struct {
	Start int64
	End int64
	Array []*DebugData_
}
func debugData_Start(io *kaitai.Stream) *DebugData_ {
	d := &DebugData_{}
	d.Start, _ = io.Pos()
	return d
}
func flattenBitBytes(b []byte) []byte {
	out := []byte{}
	for i, bit := range b {
		if i % 8 == 0 {
			out = append(out, byte(0))
		}
		out[len(out)-1] = out[len(out)-1] | (bit << (i%8))
	}
	return out
}
