// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package dfu

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"encoding/binary"
	"fmt"
	"bytes"
)


type TlvTypes int
const (
	TlvTypesKeyhash TlvTypes = 1
	TlvTypesPubkey TlvTypes = 2
	TlvTypesSha256 TlvTypes = 16
	TlvTypesSha384 TlvTypes = 17
	TlvTypesSha512 TlvTypes = 18
	TlvTypesRsa2048 TlvTypes = 32
	TlvTypesEcdsa224 TlvTypes = 33
	TlvTypesEcdsaSig TlvTypes = 34
	TlvTypesRsa3072 TlvTypes = 35
	TlvTypesEd25519 TlvTypes = 36
	TlvTypesPureSig TlvTypes = 37
	TlvTypesEncRsa2048 TlvTypes = 48
	TlvTypesEncKw TlvTypes = 49
	TlvTypesEncX25519 TlvTypes = 50
	TlvTypesEncX25519Sha TlvTypes = 51
	TlvTypesDependency TlvTypes = 64
	TlvTypesSecurityCount TlvTypes = 80
	TlvTypesBootRecord TlvTypes = 96
	TlvTypesDecompSize TlvTypes = 112
	TlvTypesDecompSha TlvTypes = 113
	TlvTypesDecompSig TlvTypes = 114
	TlvTypesCompDecSize TlvTypes = 115
	TlvTypesVid TlvTypes = 128
	TlvTypesCid TlvTypes = 129
)
var values_TlvTypes = map[TlvTypes]string{1: "Keyhash", 2: "Pubkey", 16: "Sha256", 17: "Sha384", 18: "Sha512", 32: "Rsa2048", 33: "Ecdsa224", 34: "EcdsaSig", 35: "Rsa3072", 36: "Ed25519", 37: "PureSig", 48: "EncRsa2048", 49: "EncKw", 50: "EncX25519", 51: "EncX25519Sha", 64: "Dependency", 80: "SecurityCount", 96: "BootRecord", 112: "DecompSize", 113: "DecompSha", 114: "DecompSig", 115: "CompDecSize", 128: "Vid", 129: "Cid"}
var valueValues_TlvTypes = []TlvTypes{1, 2, 16, 17, 18, 32, 33, 34, 35, 36, 37, 48, 49, 50, 51, 64, 80, 96, 112, 113, 114, 115, 128, 129}
var valueNames_TlvTypes = []string{"Keyhash", "Pubkey", "Sha256", "Sha384", "Sha512", "Rsa2048", "Ecdsa224", "EcdsaSig", "Rsa3072", "Ed25519", "PureSig", "EncRsa2048", "EncKw", "EncX25519", "EncX25519Sha", "Dependency", "SecurityCount", "BootRecord", "DecompSize", "DecompSha", "DecompSig", "CompDecSize", "Vid", "Cid"}
func (v TlvTypes) isDefined() bool {
	_, ok := values_TlvTypes[v]
	return ok
}
func (v TlvTypes) IsATlvTypes() bool {
	return v.isDefined()
}
func (v TlvTypes) String() string {
	name, ok := values_TlvTypes[v]
	if ok {
		return name
	}
	return fmt.Sprintf("TlvTypes(%d)", v)
}
func (v TlvTypes) Title() string {
	if v.IsATlvTypes() {
		return fmt.Sprintf("%s (%d)", v, v)
	}
	return v.String()
}
func TlvTypesStrings() []string {
	return valueNames_TlvTypes
}
func TlvTypesValues() []TlvTypes {
	return valueValues_TlvTypes
}
var Dfu_Fields = []string{}
type Dfu struct {
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent kaitai.Struct
	Debug_ map[string]*DebugData_
}
func NewWithParameters() *Dfu {
	return &Dfu{
	}
}

func (this Dfu) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dfu) Read(io *kaitai.Stream, parent kaitai.Struct, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	return err
}

func NewDfu(data []byte) (*Dfu, error) {
	o := &Dfu{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Dfu) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	return _t__bytes, err
}
var Header_Fields = []string{"Magic", "Loadaddr", "LenHeader", "LenProtect", "LenBody", "Flags", "Version", "Pad"}
type Header struct {
	Magic uint32
	Loadaddr uint32
	LenHeader uint16
	LenProtect uint16
	LenBody uint32
	Flags uint32
	Version *Version
	Pad uint32
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Package
	Debug_ map[string]*DebugData_
}
func NewHeaderWithParameters() *Header {
	return &Header{
	}
}

func (this Header) IO_() *kaitai.Stream {
	return this._io
}

func (this *Header) Read(io *kaitai.Stream, parent *Package, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Magic"] = debugData_Start(this._io)
	tmp1, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Magic = uint32(tmp1)
	this.Debug_["Magic"].End, _ = this._io.Pos()
	if !(this.Magic == uint32(2532554813)) {
		return kaitai.NewValidationNotEqualError(uint32(2532554813), this.Magic, this._io, "/types/header/seq/0")
	}
	this.Debug_["Loadaddr"] = debugData_Start(this._io)
	tmp2, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Loadaddr = uint32(tmp2)
	this.Debug_["Loadaddr"].End, _ = this._io.Pos()
	this.Debug_["LenHeader"] = debugData_Start(this._io)
	tmp3, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenHeader = uint16(tmp3)
	this.Debug_["LenHeader"].End, _ = this._io.Pos()
	this.Debug_["LenProtect"] = debugData_Start(this._io)
	tmp4, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenProtect = uint16(tmp4)
	this.Debug_["LenProtect"].End, _ = this._io.Pos()
	this.Debug_["LenBody"] = debugData_Start(this._io)
	tmp5, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenBody = uint32(tmp5)
	this.Debug_["LenBody"].End, _ = this._io.Pos()
	this.Debug_["Flags"] = debugData_Start(this._io)
	tmp6, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Flags = uint32(tmp6)
	this.Debug_["Flags"].End, _ = this._io.Pos()
	this.Debug_["Version"] = debugData_Start(this._io)
	tmp7 := NewVersionWithParameters()
	err = tmp7.Read(this._io, this, this._root)
	this.Version = tmp7
	if err != nil {
		return err
	}
	this.Debug_["Version"].End, _ = this._io.Pos()
	this.Debug_["Pad"] = debugData_Start(this._io)
	tmp8, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Pad = uint32(tmp8)
	this.Debug_["Pad"].End, _ = this._io.Pos()
	return err
}

func NewHeader(data []byte) (*Header, error) {
	o := &Header{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Header) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint32(this.Magic))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint32(this.Loadaddr))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint16(this.LenHeader))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint16(this.LenProtect))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint32(this.LenBody))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint32(this.Flags))
	if err != nil {
		return _t__bytes, err
	}
	if (this.Version != nil) {
		tmp9, err := this.Version.Bytes_()
		if err != nil {
			return _t__bytes, err
		}
		_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, tmp9)
		if err != nil {
			return _t__bytes, err
		}
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint32(this.Pad))
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var Package_Fields = []string{"Header", "Body", "Tlvs"}
type Package struct {
	Header *Header
	Body []byte
	Tlvs *Tlvs
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent kaitai.Struct
	_raw_Header []byte
	Debug_ map[string]*DebugData_
}
func NewPackageWithParameters() *Package {
	return &Package{
	}
}

func (this Package) IO_() *kaitai.Stream {
	return this._io
}

func (this *Package) Read(io *kaitai.Stream, parent kaitai.Struct, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Header"] = debugData_Start(this._io)
	tmp10, err := this._io.ReadBytes(int(512))
	if err != nil {
		return err
	}
	tmp10 = tmp10
	this._raw_Header = tmp10
	_io__raw_Header := kaitai.NewStream(bytes.NewReader(this._raw_Header))
	tmp11 := NewHeaderWithParameters()
	err = tmp11.Read(_io__raw_Header, this, this._root)
	this.Header = tmp11
	if err != nil {
		return err
	}
	this.Debug_["Header"].End, _ = this._io.Pos()
	this.Debug_["Body"] = debugData_Start(this._io)
	tmp12, err := this._io.ReadBytes(int(this.Header.LenBody))
	if err != nil {
		return err
	}
	tmp12 = tmp12
	this.Body = tmp12
	this.Debug_["Body"].End, _ = this._io.Pos()
	this.Debug_["Tlvs"] = debugData_Start(this._io)
	tmp13 := NewTlvsWithParameters()
	err = tmp13.Read(this._io, this, this._root)
	this.Tlvs = tmp13
	if err != nil {
		return err
	}
	this.Debug_["Tlvs"].End, _ = this._io.Pos()
	return err
}

func NewPackage(data []byte) (*Package, error) {
	o := &Package{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Package) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	if (this.Header != nil) {
		tmp14, err := this.Header.Bytes_()
		if err != nil {
			return _t__bytes, err
		}
		_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, tmp14)
		if err != nil {
			return _t__bytes, err
		}
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, this.Body)
	if err != nil {
		return _t__bytes, err
	}
	if (this.Tlvs != nil) {
		tmp15, err := this.Tlvs.Bytes_()
		if err != nil {
			return _t__bytes, err
		}
		_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, tmp15)
		if err != nil {
			return _t__bytes, err
		}
	}
	return _t__bytes, err
}
var Tlv_Fields = []string{"Type", "Pad", "LenTlvInner", "TlvInner"}
type Tlv struct {
	Type TlvTypes
	Pad uint8
	LenTlvInner uint16
	TlvInner []byte
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *TlvContainer
	Debug_ map[string]*DebugData_
}
func NewTlvWithParameters() *Tlv {
	return &Tlv{
	}
}

func (this Tlv) IO_() *kaitai.Stream {
	return this._io
}

func (this *Tlv) Read(io *kaitai.Stream, parent *TlvContainer, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Type"] = debugData_Start(this._io)
	tmp16, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Type = TlvTypes(tmp16)
	this.Debug_["Type"].End, _ = this._io.Pos()
	this.Debug_["Pad"] = debugData_Start(this._io)
	tmp17, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Pad = tmp17
	this.Debug_["Pad"].End, _ = this._io.Pos()
	this.Debug_["LenTlvInner"] = debugData_Start(this._io)
	tmp18, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenTlvInner = uint16(tmp18)
	this.Debug_["LenTlvInner"].End, _ = this._io.Pos()
	this.Debug_["TlvInner"] = debugData_Start(this._io)
	tmp19, err := this._io.ReadBytes(int(this.LenTlvInner))
	if err != nil {
		return err
	}
	tmp19 = tmp19
	this.TlvInner = tmp19
	this.Debug_["TlvInner"].End, _ = this._io.Pos()
	return err
}

func NewTlv(data []byte) (*Tlv, error) {
	o := &Tlv{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Tlv) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint8(this.Type))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, this.Pad)
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint16(this.LenTlvInner))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, this.TlvInner)
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var TlvContainer_Fields = []string{"Tlv"}
type TlvContainer struct {
	Tlv []*Tlv // dynamic size
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Tlvs
	Debug_ map[string]*DebugData_
}
func NewTlvContainerWithParameters() *TlvContainer {
	return &TlvContainer{
	}
}

func (this TlvContainer) IO_() *kaitai.Stream {
	return this._io
}

func (this *TlvContainer) Read(io *kaitai.Stream, parent *Tlvs, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Tlv"] = debugData_Start(this._io)
	for i := 0;; i++ {
		tmp20, err := this._io.EOF()
		if err != nil {
			return err
		}
		if tmp20 {
			break
		}
		this.Debug_["Tlv"].Array = append(this.Debug_["Tlv"].Array, debugData_Start(this._io))
		tmp21 := NewTlvWithParameters()
		err = tmp21.Read(this._io, this, this._root)
		this.Tlv = append(this.Tlv, tmp21)
		if err != nil {
			return err
		}
		this.Debug_["Tlv"].Array[len(this.Tlv) - 1].End, _ = this._io.Pos()
	}
	this.Debug_["Tlv"].End, _ = this._io.Pos()
	return err
}

func NewTlvContainer(data []byte) (*TlvContainer, error) {
	o := &TlvContainer{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *TlvContainer) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	if this.Tlv == nil {
		_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, make([]byte, 0))
		if err != nil {
			return _t__bytes, err
		}
	} else {
		for i := range this.Tlv {
			_ = i
			if (this.Tlv != nil) {
				if this.Tlv[i] == nil {
					_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, []byte{0})
					if err != nil {
						return _t__bytes, err
					}
				} else {
					tmp22, err := this.Tlv[i].Bytes_()
					if err != nil {
						return _t__bytes, err
					}
					_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, tmp22)
					if err != nil {
						return _t__bytes, err
					}
				}
			}
		}
	}
	return _t__bytes, err
}
var Tlvs_Fields = []string{"Magic", "Size", "TlvContainer"}
type Tlvs struct {
	Magic uint16
	Size uint16
	TlvContainer *TlvContainer
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Package
	_raw_TlvContainer []byte
	Debug_ map[string]*DebugData_
}
func NewTlvsWithParameters() *Tlvs {
	return &Tlvs{
	}
}

func (this Tlvs) IO_() *kaitai.Stream {
	return this._io
}

func (this *Tlvs) Read(io *kaitai.Stream, parent *Package, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Magic"] = debugData_Start(this._io)
	tmp23, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Magic = uint16(tmp23)
	this.Debug_["Magic"].End, _ = this._io.Pos()
	if !(this.Magic == 26887) {
		return kaitai.NewValidationNotEqualError(26887, this.Magic, this._io, "/types/tlvs/seq/0")
	}
	this.Debug_["Size"] = debugData_Start(this._io)
	tmp24, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Size = uint16(tmp24)
	this.Debug_["Size"].End, _ = this._io.Pos()
	this.Debug_["TlvContainer"] = debugData_Start(this._io)
	tmp25, err := this._io.ReadBytes(int(this.Size - 4))
	if err != nil {
		return err
	}
	tmp25 = tmp25
	this._raw_TlvContainer = tmp25
	_io__raw_TlvContainer := kaitai.NewStream(bytes.NewReader(this._raw_TlvContainer))
	tmp26 := NewTlvContainerWithParameters()
	err = tmp26.Read(_io__raw_TlvContainer, this, this._root)
	this.TlvContainer = tmp26
	if err != nil {
		return err
	}
	this.Debug_["TlvContainer"].End, _ = this._io.Pos()
	return err
}

func NewTlvs(data []byte) (*Tlvs, error) {
	o := &Tlvs{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Tlvs) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint16(this.Magic))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint16(this.Size))
	if err != nil {
		return _t__bytes, err
	}
	if (this.TlvContainer != nil) {
		tmp27, err := this.TlvContainer.Bytes_()
		if err != nil {
			return _t__bytes, err
		}
		_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, tmp27)
		if err != nil {
			return _t__bytes, err
		}
	}
	return _t__bytes, err
}
var Version_Fields = []string{"Major", "Minor", "Revision", "Buildnum"}
type Version struct {
	Major uint8
	Minor uint8
	Revision uint16
	Buildnum uint32
	_io *kaitai.Stream
	_root kaitai.Struct
	_parent *Header
	Debug_ map[string]*DebugData_
}
func NewVersionWithParameters() *Version {
	return &Version{
	}
}

func (this Version) IO_() *kaitai.Stream {
	return this._io
}

func (this *Version) Read(io *kaitai.Stream, parent *Header, root kaitai.Struct) (err error) {
	this._io = io
	this._parent = parent
	this._root = root
	this.Debug_ = map[string]*DebugData_{}

	this.Debug_["Major"] = debugData_Start(this._io)
	tmp28, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Major = tmp28
	this.Debug_["Major"].End, _ = this._io.Pos()
	this.Debug_["Minor"] = debugData_Start(this._io)
	tmp29, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Minor = tmp29
	this.Debug_["Minor"].End, _ = this._io.Pos()
	this.Debug_["Revision"] = debugData_Start(this._io)
	tmp30, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Revision = uint16(tmp30)
	this.Debug_["Revision"].End, _ = this._io.Pos()
	this.Debug_["Buildnum"] = debugData_Start(this._io)
	tmp31, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Buildnum = uint32(tmp31)
	this.Debug_["Buildnum"].End, _ = this._io.Pos()
	return err
}

func NewVersion(data []byte) (*Version, error) {
	o := &Version{}
	return o, o.Read(kaitai.NewStream(bytes.NewReader(data)), nil, o)
}

func (this *Version) Bytes_() ([]byte, error) {
	var (
		err error
		_t__bytes []byte
	)

	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, this.Major)
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, this.Minor)
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint16(this.Revision))
	if err != nil {
		return _t__bytes, err
	}
	_t__bytes, err = binary.Append(_t__bytes, binary.LittleEndian, uint32(this.Buildnum))
	if err != nil {
		return _t__bytes, err
	}
	return _t__bytes, err
}
var DefinedEnumValues = map[interface{}][]int{TlvTypes(0):{1,2,16,17,18,32,33,34,35,36,37,48,49,50,51,64,80,96,112,113,114,115,128,129}}
type DebugData_ struct {
	Start int64
	End int64
	Array []*DebugData_
}
func debugData_Start(io *kaitai.Stream) *DebugData_ {
	d := &DebugData_{}
	d.Start, _ = io.Pos()
	return d
}
func flattenBitBytes(b []byte) []byte {
	out := []byte{}
	for i, bit := range b {
		if i % 8 == 0 {
			out = append(out, byte(0))
		}
		out[len(out)-1] = out[len(out)-1] | (bit << (i%8))
	}
	return out
}
